--
-- TABLE STRUCTURE FOR TABLE DOMAIN
--
CREATE TABLE DOMAIN (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  CODE VARCHAR(255) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  ORDERING BIGINT(20) DEFAULT NULL,
  TYPE VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE REPORT
--
CREATE TABLE REPORT (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(250) DEFAULT NULL,
  PRODUCT_CODE VARCHAR(255) DEFAULT NULL,
  REPORT_DEFINITION VARCHAR(255) DEFAULT NULL,
  REPORT_ENGINE_ID VARCHAR(255) DEFAULT NULL,
  REPORT_TYPE_ID VARCHAR(255) DEFAULT NULL,
  STATUS_ID VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_REPORT_ENGINE_ID (REPORT_ENGINE_ID),
  KEY FK_REPORT_TYPE_ID (REPORT_TYPE_ID),
  KEY FK_REPORT_STATUS (STATUS_ID),
  CONSTRAINT FK_REPORT_ENGINE_ID FOREIGN KEY (REPORT_ENGINE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REPORT_TYPE_ID FOREIGN KEY (REPORT_TYPE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REPORT_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX INDX_REPORT_PRODUCT_CODE ON REPORT (PRODUCT_CODE);

--
-- TABLE STRUCTURE FOR TABLE SCORING
--
CREATE TABLE SCORING (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ACRONYM VARCHAR(255) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  SCORING_DEFINITION VARCHAR(255) DEFAULT NULL,
  SCORING_ENGINE_ID VARCHAR(255) DEFAULT NULL,
  SCORING_TYPE_ID VARCHAR(255) DEFAULT NULL,
  STATUS_ID VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_SCORING_ENGINE_ID (SCORING_ENGINE_ID),
  KEY FK_SCORING_TYPE_ID (SCORING_TYPE_ID),
  KEY FK_SCORING_STATUS (STATUS_ID),
  CONSTRAINT FK_SCORING_ENGINE_ID FOREIGN KEY (SCORING_ENGINE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SCORING_TYPE_ID FOREIGN KEY (SCORING_TYPE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SCORING_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX INDX_SCORING_ACRONYM ON SCORING (ACRONYM);

--
-- TABLE STRUCTURE FOR TABLE BUSINESS_UNIT
--

CREATE TABLE BUSINESS_UNIT (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	ALLOW_USER_CREATION BIT(1) DEFAULT NULL,
	COUNTRY_ID VARCHAR(255) DEFAULT NULL,
	DATE_FORMAT_ID VARCHAR(255) DEFAULT NULL,
	FIRST_NAME VARCHAR(255) DEFAULT NULL,
	GUID VARCHAR(255) DEFAULT NULL,
	LANGUAGE_ID VARCHAR(255) DEFAULT NULL,
	LAST_NAME VARCHAR(255) DEFAULT NULL,
	MAIN_CONTACT_EMAIL VARCHAR(255) DEFAULT NULL,
	MAIN_CONTACT_PHONE VARCHAR(255) DEFAULT NULL,
	MIDDLE_NAME VARCHAR(255) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	NUMBER_FORMAT_ID VARCHAR(255) DEFAULT NULL,
	PASSWORD_EXPIRY_DAYS INT(11) DEFAULT NULL,
	STATUS VARCHAR(255) DEFAULT NULL,
	TIMEZONE_ID VARCHAR(255) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE ACCOUNT
--

CREATE TABLE ACCOUNT (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	ACCOUNT_NUMBER VARCHAR(255) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	OWNER_FIRST_NAME VARCHAR(255) DEFAULT NULL,
	OWNER_LAST_NAME VARCHAR(255) DEFAULT NULL,
	OWNER_NUMBER VARCHAR(255) DEFAULT NULL,
	BUSINESS_UNIT_ID CHAR(32) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	KEY FK_ACC_BUSINESSUNIT (BUSINESS_UNIT_ID),
	CONSTRAINT FK_ACC_BUSINESSUNIT FOREIGN KEY (BUSINESS_UNIT_ID) REFERENCES BUSINESS_UNIT (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE ASSESS_TEST_DOMAIN
--

CREATE TABLE ASSESS_TEST_DOMAIN (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	UNIQUE KEY UK_ASSESS_TST_DOMAIN (NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE ASSESS_SUBTEST_TYPE
--

/*!40101 SET @SAVED_CS_CLIENT     = @@CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_CLIENT = UTF8 */;
CREATE TABLE ASSESS_SUBTEST_TYPE (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	UNIQUE KEY UK_ASSESS_SUBTST_TYPE (NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE ASSESS_TEST
--


CREATE TABLE ASSESS_TEST (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL,
	DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
	GUID VARCHAR(255) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	NORM_TYPE VARCHAR(255) DEFAULT NULL,
	OBSERVATIONS_ENABLED BIT(1) DEFAULT NULL,
	USE_QG_COMPARISON_API BIT(1) DEFAULT NULL,
	DOMAIN_ID CHAR(32) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	KEY FK_ASSESS_TEST_DOMAIN (DOMAIN_ID),
	CONSTRAINT FK_ASSESS_TEST_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES ASSESS_TEST_DOMAIN (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE ASSESS_SUBTEST
--

CREATE TABLE ASSESS_SUBTEST (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	ABBREVIATION VARCHAR(255) DEFAULT NULL,
	AVERAGE_DURATION INT(11) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL,
	DISABLED BIT(1) DEFAULT NULL,
	DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
	GUID VARCHAR(255) DEFAULT NULL,
	MAX_AGE INT(11) DEFAULT NULL,
	MAX_AGE_MONTHS INT(11) DEFAULT NULL,
	MAX_DELAY_MINUTES INT(11) DEFAULT NULL,
	MIN_AGE INT(11) DEFAULT NULL,
	MIN_AGE_MONTHS INT(11) DEFAULT NULL,
	MIN_DELAY_MINUTES INT(11) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	OBSERVATIONS_ENABLED BIT(1) DEFAULT NULL,
	USES_STIM BIT(1) DEFAULT NULL,
	SUBTEST_TYPE_ID CHAR(32) DEFAULT NULL,
	TEST_ID CHAR(32) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	KEY FK_ASSESS_SUBTST_TYPE (SUBTEST_TYPE_ID),
	KEY FK_ASSESS_TEST (TEST_ID),
	CONSTRAINT FK_ASSESS_TEST FOREIGN KEY (TEST_ID) REFERENCES ASSESS_TEST (ID),
	CONSTRAINT FK_ASSESS_SUBTST_TYPE FOREIGN KEY (SUBTEST_TYPE_ID) REFERENCES ASSESS_SUBTEST_TYPE (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE ASSESSMENT
--

CREATE TABLE ASSESSMENT (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ACRONYM VARCHAR(255) DEFAULT NULL,
  API_ENABLED BIT(1) DEFAULT NULL,
  ASSESSMENT_DEFINITION VARCHAR(255) DEFAULT NULL,
  COMMENTS LONGTEXT,
  CONFIG_SOURCE_ID VARCHAR(255) DEFAULT NULL,
  DATA_COLLECTION_ENABLED BIT(1) DEFAULT NULL,
  DEFINITION_JSON LONGTEXT,
  EXPIRY_DATE DATETIME DEFAULT NULL,
  GUID VARCHAR(255) DEFAULT NULL,
  LICENSED_BY VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  PRODUCT_CODE VARCHAR(255) DEFAULT NULL,
  QGI_VERSION VARCHAR(255) DEFAULT NULL,
  REQUIRED_QUAL_LEVEL VARCHAR(255) DEFAULT NULL,
  START_DATE DATETIME DEFAULT NULL,
  STATUS_ID VARCHAR(255) DEFAULT NULL,
  TYPE_ID VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_ASSESSMENT_TYPE (TYPE_ID),
  KEY FK_ASSESSMENT_STATUS (STATUS_ID),
  CONSTRAINT FK_ASSESSMENT_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ASSESSMENT_TYPE FOREIGN KEY (TYPE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX INDX_ASSESSMENT_ACRONYM ON ASSESSMENT (ACRONYM);

--
-- TABLE STRUCTURE FOR TABLE ASSESSMENT_REPORT
--
CREATE TABLE ASSESSMENT_REPORT (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ASSESSMENT_ID VARCHAR(255) DEFAULT NULL,
  REPORT_ID VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_ASSESSMENT_REP_ASMT_ID (ASSESSMENT_ID),
  KEY FK_ASSESSMENT_REPORT_ID (REPORT_ID),
  CONSTRAINT FK_ASSESSMENT_REP_ASMT_ID FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ASSESSMENT_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES REPORT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE ASSESSMENT_SCORING
--
CREATE TABLE ASSESSMENT_SCORING (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ASSESSMENT_ID VARCHAR(255) DEFAULT NULL,
  SCORING_ID VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_ASSESSMENT_SCORING_ASMT_ID (ASSESSMENT_ID),
  KEY FK_ASSESSMENT_SCORING_ID (SCORING_ID),
  CONSTRAINT FK_ASSESSMENT_SCORING_ASMT_ID FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ASSESSMENT_SCORING_ID FOREIGN KEY (SCORING_ID) REFERENCES SCORING (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;



--
-- TABLE STRUCTURE FOR TABLE BUSINESS_UNIT_ASSESSMENT
--
CREATE TABLE BUSINESS_UNIT_ASSESSMENT (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	COMMENTS LONGTEXT,
	ISBN VARCHAR(255) DEFAULT NULL,
	STATUS VARCHAR(255) DEFAULT NULL,
	WEBSITE_LINK VARCHAR(255) DEFAULT NULL,
	ASSESSMENT_ID CHAR(32) DEFAULT NULL,
	BUSINESS_UNIT_ID CHAR(32) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	KEY FK_BU_ASSESSMENT_ID (ASSESSMENT_ID),
	KEY FK_BU_BUSINESS_UNIT_ID (BUSINESS_UNIT_ID),
	CONSTRAINT FK_BU_ASSESSMENT_ID FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ID),
	CONSTRAINT FK_BU_BUSINESS_UNIT_ID FOREIGN KEY (BUSINESS_UNIT_ID) REFERENCES BUSINESS_UNIT (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE RESOURCE_META_DATA
--
CREATE TABLE RESOURCE_META_DATA (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	RESOURCE_KEY VARCHAR(255) NOT NULL,
	RESOURCE_TYPE VARCHAR(255) DEFAULT NULL,
	RESOURCE_VALUE VARCHAR(255) NOT NULL,
	BUSINESS_UNIT_ID CHAR(32) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	UNIQUE KEY UK_RSMDATA_KEY_BU (BUSINESS_UNIT_ID,RESOURCE_KEY),
	KEY FK_RSMD_BU_ID (BUSINESS_UNIT_ID),
	CONSTRAINT FK_RSMD_BU_ID FOREIGN KEY (BUSINESS_UNIT_ID) REFERENCES BUSINESS_UNIT (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE USER_ACCOUNT
--
CREATE TABLE USER_ACCOUNT (
	ID CHAR(32) NOT NULL,
	CREATED_BY VARCHAR(255) DEFAULT NULL,
	LAST_CREATED DATETIME DEFAULT NULL,
	LAST_UPDATED DATETIME DEFAULT NULL,
	UPDATED_BY VARCHAR(255) DEFAULT NULL,
	VERSION BIGINT(20) DEFAULT NULL,
	USER_ID VARCHAR(255) DEFAULT NULL,
	ACCOUNT_ID CHAR(32) DEFAULT NULL,
	DELETED_BY VARCHAR(255) DEFAULT NULL,
	DATE_DELETED DATETIME DEFAULT NULL,
	DELETED BIT(1) DEFAULT '\0',
	PRIMARY KEY (ID),
	KEY FK_USER_ACCOUNT_ID (ACCOUNT_ID),
	CONSTRAINT FK_USER_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE CONTENT_TYPE
--

CREATE TABLE CONTENT_TYPE (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
  LOCALIZATION_KEY VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  USES_MANIFEST BIT(1) DEFAULT NULL,
  TEST_ID CHAR(32) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_CONTENT_TYPE_NAME (NAME),
  KEY FK_CONTENT_TYPE_TEST (TEST_ID),
  CONSTRAINT FK_CONTENT_TYPE_TEST FOREIGN KEY (TEST_ID) REFERENCES ASSESS_TEST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE CONTENT_VERSION
--
CREATE TABLE CONTENT_VERSION (
  ID char(32) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  DATE_DELETED datetime DEFAULT NULL,
  DELETED bit(1) DEFAULT '\0',
  DELETED_BY varchar(255) DEFAULT NULL,
  LAST_CREATED datetime DEFAULT NULL,
  LAST_UPDATED datetime DEFAULT NULL,
  UPDATED_BY varchar(255) DEFAULT NULL,
  VERSION bigint(20) DEFAULT NULL,
  BRANCH varchar(255) DEFAULT NULL,
  CONFIG varchar(255) DEFAULT NULL,
  DATE_VERSION datetime DEFAULT NULL,
  FILE_SIZE bigint(20) DEFAULT NULL,
  HASH varchar(255) DEFAULT NULL,
  INTERFACE_MANIFEST varchar(255) DEFAULT NULL,
  ORIGINAL_FILE_NAME varchar(255) DEFAULT NULL,
  PATH_RELATIVE_TO_ZIP_DIR varchar(255) DEFAULT NULL,
  PARENT_ID char(32) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_CONTENT_VERSION_TYPE (PARENT_ID),
  CONSTRAINT FK_CONTENT_VERSION_TYPE FOREIGN KEY (PARENT_ID) REFERENCES CONTENT_TYPE (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

--
-- TABLE STRUCTURE FOR TABLE FORM
--

CREATE TABLE FORM (
  ID CHAR(32) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ACRONYM VARCHAR(255) DEFAULT NULL,
  DATE_COLLECTION_EXPORT_DEF LONGTEXT,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  FORM_DEFINITION LONGTEXT,
  FORM_TYPE VARCHAR(255) DEFAULT NULL,
  GROUP_ADMINISTRATION VARCHAR(1) DEFAULT NULL,
  OSA_ENGINE_ID BIGINT(20) NOT NULL,
  PRODUCT_CODE VARCHAR(255) DEFAULT NULL,
  STATUS_ID VARCHAR(255) DEFAULT NULL,
  ASSESSMENT_ID CHAR(32) DEFAULT NULL,
  PARENT_FORM_ID CHAR(32) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_FORM_ASSESSMENT_ID (ASSESSMENT_ID),
  KEY FK_FORM_TO_PARENT_FORM_ID (PARENT_FORM_ID),
  KEY FK_FORM_STATUS (STATUS_ID),
  CONSTRAINT FK_FORM_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_FORM_ASSESSMENT_ID FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_FORM_TO_PARENT_FORM_ID FOREIGN KEY (PARENT_FORM_ID) REFERENCES FORM (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX INDX_FORM_ACRONYM ON FORM (ACRONYM);
CREATE INDEX INDX_FORM_PRODUCT_CODE ON FORM (PRODUCT_CODE);



CREATE TABLE FORM_DELIVERY_TYPE (
  ID char(32) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  DATE_DELETED datetime DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY varchar(255) DEFAULT NULL,
  LAST_CREATED datetime DEFAULT NULL,
  LAST_UPDATED datetime DEFAULT NULL,
  UPDATED_BY varchar(255) DEFAULT NULL,
  VERSION bigint(20) DEFAULT NULL,
  DELIVERY_TYPE_ID varchar(255) DEFAULT NULL,
  FORM_ID varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_ASSESSMENT_FRM_DEL_FRM_ID (FORM_ID),
  KEY FK_ASSESSMENT_FRM_DEL_DEL_ID (DELIVERY_TYPE_ID),
  CONSTRAINT FK_ASSESSMENT_FRM_DEL_FRM_ID FOREIGN KEY (FORM_ID) REFERENCES FORM (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ASSESSMENT_FRM_DEL_DEL_ID FOREIGN KEY (DELIVERY_TYPE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE FORM_OSA_MAP (
  ID char(32) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  DATE_DELETED datetime DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY varchar(255) DEFAULT NULL,
  LAST_CREATED datetime DEFAULT NULL,
  LAST_UPDATED datetime DEFAULT NULL,
  UPDATED_BY varchar(255) DEFAULT NULL,
  VERSION bigint(20) DEFAULT NULL,
  FORM_ID varchar(255) DEFAULT NULL,
  OSA_FORM_MAP longtext,
  PRIMARY KEY (ID),
  KEY FORM_OSA_MAP_FK (FORM_ID),
  CONSTRAINT FK_FORM_OSA_MAP FOREIGN KEY (FORM_ID) REFERENCES FORM (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE REPORT_OUTPUT_TYPE (
  ID char(32) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  DATE_DELETED datetime DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY varchar(255) DEFAULT NULL,
  LAST_CREATED datetime DEFAULT NULL,
  LAST_UPDATED datetime DEFAULT NULL,
  UPDATED_BY varchar(255) DEFAULT NULL,
  VERSION bigint(20) DEFAULT NULL,
  REPORT_ID varchar(255) DEFAULT NULL,
  REPORT_OUTPUT_TYPE_ID varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_REPORT_OUTPUT_TYPE_ID (REPORT_OUTPUT_TYPE_ID),
  KEY FK_REPORT_OUTPUT_REPORT_ID (REPORT_ID),
  CONSTRAINT FK_REPORT_OUTPUT_TYPE_ID FOREIGN KEY (REPORT_OUTPUT_TYPE_ID) REFERENCES DOMAIN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REPORT_OUTPUT_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES REPORT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE FORM_REPORT_ASC (
   ID char(40) NOT NULL,
   ASSESSMENT_ID char(40) NOT NULL,
   FORM_ID char(40) NOT NULL,
   REPORT_ID char(40) NOT NULL,
   PRIMARY KEY (ID),
   KEY FK_FRA_ASSESSMENT (ASSESSMENT_ID),
   KEY FK_FRA_FORM (FORM_ID),
   KEY FK_FRA_REPORT (REPORT_ID),
   CONSTRAINT FK_FRA_ASSESSMENT FOREIGN KEY (ASSESSMENT_ID) REFERENCES ASSESSMENT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT FK_FRA_FORM FOREIGN KEY (FORM_ID) REFERENCES FORM (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT FK_FRA_REPORT FOREIGN KEY (REPORT_ID) REFERENCES REPORT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE FORM_SCORING_REPORT (
  ID char(32) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  DATE_DELETED datetime DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  DELETED_BY varchar(255) DEFAULT NULL,
  LAST_CREATED datetime DEFAULT NULL,
  LAST_UPDATED datetime DEFAULT NULL,
  UPDATED_BY varchar(255) DEFAULT NULL,
  VERSION bigint(20) DEFAULT NULL,
  IS_COMBO_PARENT bit(1) DEFAULT NULL,
  COMBO_SCORING_ID varchar(255) DEFAULT NULL,
  FORM_ID varchar(255) DEFAULT NULL,
  FORM_SCORING_MAP longtext,
  PARENT_FORM_SCORING_REPORT_ID varchar(255) DEFAULT NULL,
  REPORT_ID varchar(255) DEFAULT NULL,
  SCORING_COMBO_SCORING_MAP longtext,
  SCORING_ID varchar(255) DEFAULT NULL,
  SCORING_REPORT_MAP longtext,
  UPDATE_FLAG char(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_COMBO_SCORING_ID (COMBO_SCORING_ID),
  KEY FK_FORM_ID (FORM_ID),
  KEY FK_FSR_REPORT_ID (REPORT_ID),
  KEY FK_SCORING_ID (SCORING_ID),
  CONSTRAINT FK_COMBO_SCORING_ID FOREIGN KEY (COMBO_SCORING_ID) REFERENCES SCORING (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_FORM_ID FOREIGN KEY (FORM_ID) REFERENCES FORM (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_FSR_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES REPORT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SCORING_ID FOREIGN KEY (SCORING_ID) REFERENCES SCORING (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE FORM_ASSESS_TEST (
  ASSESS_TEST_ID CHAR(32) DEFAULT NULL,
  ID CHAR(32) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_FORM_ASSESS_TEST_ID (ASSESS_TEST_ID),
  KEY FK_FORM_ASSESS_ID (ID),
  CONSTRAINT FK_FORM_ASSESS_TEST_ID FOREIGN KEY (ASSESS_TEST_ID) REFERENCES ASSESS_TEST (ID),
  CONSTRAINT FK_FORM_ASSESS_ID FOREIGN KEY (ID) REFERENCES ASSESSMENT (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX INDX_FORM_ASSESS_TEST ON FORM_ASSESS_TEST (ASSESS_TEST_ID);



