--
-- TABLE STRUCTURE FOR TABLE APP_ROLE
--

DROP TABLE IF EXISTS APP_ROLE;

CREATE TABLE APP_ROLE (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  AUTHORITY VARCHAR(255) NOT NULL,
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  PRIMARY KEY (ID),
  UNIQUE KEY UK_APPROLE_AUTH (AUTHORITY)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE APP_USER
--

DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ACCOUNT_EXPIRED BIT(1) NOT NULL,
  ACCOUNT_LOCKED BIT(1) NOT NULL,
  CONFIRMED BIT(1) NOT NULL,
  ENABLED BIT(1) NOT NULL,
  FAILED_LOGINS INT(11) DEFAULT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  HONORIFIC VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  LAST_UNLOCKED DATETIME DEFAULT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  TIMEZONE_ID VARCHAR(255) DEFAULT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  PRIMARY KEY (ID),
  UNIQUE KEY UK_APPUSR_NAME (USERNAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE APP_USER_ROLES
--

DROP TABLE IF EXISTS APP_USER_ROLES;

CREATE TABLE APP_USER_ROLES (
  USER_ID CHAR(32) NOT NULL,
  ROLE_ID CHAR(32) NOT NULL,
  KEY FK_APPROLE_ROLE_ID (ROLE_ID),
  KEY FK_APPROLE_USER_ID (USER_ID),
  CONSTRAINT FK_APPROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
  CONSTRAINT FK_APPROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE OAUTH_CLIENT_DETAILS
--

DROP TABLE IF EXISTS OAUTH_CLIENT_DETAILS;

CREATE TABLE OAUTH_CLIENT_DETAILS (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  ACCESS_TOKEN_VALIDITY INT(11) DEFAULT NULL,
  ADDITIONAL_INFORMATION VARCHAR(1024) DEFAULT NULL,
  AUTHORITIES VARCHAR(255) DEFAULT NULL,
  AUTHORIZED_GRANT_TYPES VARCHAR(255) DEFAULT NULL,
  AUTO_APPROVE VARCHAR(255) DEFAULT NULL,
  CLIENT_ID VARCHAR(255) DEFAULT NULL,
  CLIENT_SECRET VARCHAR(255) DEFAULT NULL,
  REFRESH_TOKEN_VALIDITY INT(11) DEFAULT NULL,
  RESOURCE_IDS VARCHAR(255) DEFAULT NULL,
  SCOPE VARCHAR(255) DEFAULT NULL,
  WEB_SERVER_REDIRECT_URI VARCHAR(255) DEFAULT NULL,
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  PRIMARY KEY (ID),
  UNIQUE KEY UK_OAUTH_CLIENT_ID (CLIENT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


--
-- TABLE STRUCTURE FOR TABLE PASSWORD_HISTORY
--

DROP TABLE IF EXISTS PASSWORD_HISTORY;

CREATE TABLE PASSWORD_HISTORY (
  ID CHAR(32) NOT NULL,
  CREATED_BY VARCHAR(255) DEFAULT NULL,
  LAST_CREATED DATETIME DEFAULT NULL,
  LAST_UPDATED DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  VERSION BIGINT(20) DEFAULT NULL,
  PASSWORD VARCHAR(255) DEFAULT NULL,
  USER_ID CHAR(32) DEFAULT NULL,
  DELETED_BY VARCHAR(255) DEFAULT NULL,
  DATE_DELETED DATETIME DEFAULT NULL,
  DELETED BIT(1) DEFAULT '\0',
  PRIMARY KEY (ID),
  KEY FKPWD_HISTORY_USER_ID (USER_ID),
  CONSTRAINT FKPWD_HISTORY_USER_ID FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


